### ISSUE TITLE
The process.py consistency checks do not accept input variable runtitle

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1073]
In GitLab by @ajpearcey on Jul 15, 2020, 15:52

When running process as a python script it fails when checking the input variables in IN.DAT for the input `runtitle`. If this line of the IN.DAT is removed then it runs successfully. 

The error spit out into the terminal is:
```
apearce@ajpearceyVM:~/work/PROCESS/testing_folder$ python ~/work/PROCESS/process.py 
Running process.py
Traceback (most recent call last):
  File "/home/apearce/work/PROCESS/process.py", line 10, in <module>
    main()
  File "/home/apearce/work/PROCESS/utilities/process.py", line 221, in main
    Process()
  File "/home/apearce/work/PROCESS/utilities/process.py", line 42, in __init__
    self.validate_input()
  File "/home/apearce/work/PROCESS/utilities/process.py", line 206, in validate_input
    input_validator.validate(self.input)
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/input_validator.py", line 136, in validate
    rule_list = RuleList(input_file_path)
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/input_validator.py", line 26, in __init__
    self.data = in_dat.StructuredInputData(filename=input_file_path)
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/in_dat.py", line 1403, in __init__
    use_string_values=False)
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/in_dat.py", line 405, in get_parameters
    line_value = data[item].get_value
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/in_dat.py", line 858, in get_value
    return parameter_type(self.name, self.value)
  File "/home/apearce/work/PROCESS/utilities/process_io_lib/in_dat.py", line 674, in parameter_type
    param_type = DICT_VAR_TYPE[name]
KeyError: 'runtitle'
```
The identical IN.DAT will run with no issues if run using run_process.py

ref @jonmaddock

**Comment by clmould** [comment]
I can't recreate this error as `process.py` has been removed. I was able to run `python process/main.py -i tests/integration/data/large_tokamak_IN.DAT` and this worked as expected and did not throw any errors, so will close the issue
