### ISSUE TITLE
plot_proc.py fails if no optimization is carried out

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1418]
In GitLab by @pc6783 on Oct 8, 2021, 18:12

plot_proc.py works fine... except if the input MFILE does not report `minmax`, as is the case if `ioptimz` is -1 or -2. Then it fails with a python error:

`Key 'minmax' not in MFILE. KeyError! Check MFILE
Traceback (most recent call last):
  File "process/io/plot_proc.py", line 2734, in <module>
    main()
  File "process/io/plot_proc.py", line 2715, in main
    main_plot(page1, page2, m_file, scan=scan, plasmod=pmod_switch, demo_ranges=demo_ranges)
  File "process/io/plot_proc.py", line 2141, in main_plot
    plot_header(plot_1, m_file_data, scan)
  File "process/io/plot_proc.py", line 1562, in plot_header
    ("!" + proc_dict['DICT_OPTIMISATION_VARS']
KeyError: '0'`

I think this should be a quick one.

**Comment by timothy-nunn** [comment]
@clmould again, may be fixed. I believe this refers to once-through files

**Comment by kj5248** [comment]
Ran plot_proc on the large_tokamak_once_through regression file and it worked without issue
