### ISSUE TITLE
N-dim scan not finding solutions and visualisation does not plot, for N = 1

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#595]
In GitLab by @kellis on Jan 3, 2018, 15:54

[test_NdimScan1.zip](https://git.ccfe.ac.uk/process/process/uploads/decb3afa8dba108ae4045515f9f908c7/test_NdimScan1.zip)
See attached project.

I tried to use the n-dimensional scan feature to scan over a single variable which is not included in scan module.

The variable I want to scan is boundl(18) - lower bound of q. In the .json file you can see I have requested 6 steps between 3.0 and 3.5.

When running the tool "ndscan_and_package.py' no feasible solutions are found:
ifail
[ 0.  6.  0.  0.  6.  6.]

When trying to plot these results using "ndscan_visualisation.py" and having chosen the appropriate options, I get the stacktrace below:

------------------------------------------------------
```
And what plotting routine would you like?
1) Contour
2) Scatter w/ Z Coloring
Please choose!:2

xdim is boundl(18) ydim is boundl(18)
Traceback (most recent call last):
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/colors.py", line 141, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (0.0, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/colors.py", line 192, in _to_rgba_no_colorcycle
    c = tuple(map(float, c))
TypeError: 'numpy.float32' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hlux/process/process_DEMORefMar2017/utilities/ndscan_visualisation.py", line 34, in <module>
    VISUTIL.main()
  File "/home/hlux/process/process_DEMORefMar2017/utilities/process_io_lib/ndscan_vis.py", line 380, in main
    masterconfigs)
  File "/home/hlux/process/process_DEMORefMar2017/utilities/process_io_lib/ndscan_vis.py", line 97, in make_scatter_plot
    pl.scatter(xarr, yarr, c=zarr, marker='s')
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3435, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4028, in scatter
    alpha=alpha
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/collections.py", line 890, in __init__
    Collection.__init__(self, **kwargs)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/collections.py", line 139, in __init__
    self.set_facecolor(facecolors)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/collections.py", line 674, in set_facecolor
    self._set_facecolor(c)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/collections.py", line 659, in _set_facecolor
    self._facecolors = mcolors.to_rgba_array(c, self._alpha)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/colors.py", line 237, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/colors.py", line 143, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/usr/local/depot/Python-3.5.1/lib/python3.5/site-packages/matplotlib/colors.py", line 194, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 0.0
kellis@freia006>
```

**Comment by timothy-nunn** [comment]
Not applicable due to #3177
